services:
  app:
    build: ./app
    env_file: 'example.env'
    ports:
      - "8050:8050"
      - depends_on:
        - llm
  llm:
    provider:
      type: model
      options:
        model: ${LLM_MODEL_NAME: - ai/smallm2:latest}
      
