services:
  app:
    build: ./app
    container_name: streamlit-app
    env_file: 'example.env'
    ports:
      - "8050:8050"
    environment:
      - BASE_URL=http://llm:8000/v1
    depends_on:
        - llm
    restart: unless-stopped
    
  llm:
    provider:
      type: model
      options:
        model: ${LLM_MODEL_NAME: - ai/smallm2:latest}
          ports:
            - "8000:8000"
        restart: unless-stopped

#   llm:
#     image: ai/smallm2:latest   # replace with your model runner image
#     container_name: llm
#     ports:
#       - "8000:8000"
#     restart: unless-stopped
